from seleniumbase import BaseCase

class Login(BaseCase):
    def test_LoginCase1(driver):
        driver.open("https://prezent-uatstaging.myprezent.com/signin")
        driver.assert_element("#username")
        driver.type("#username", "engg_user.noreply@prezent.ai")
        driver.click("#continue")
        driver.type("#password", "kiqjemkh")
        driver.click("#submit")
        driver.wait(12)
        driver.wait_for_element("//div[@class='v-avatar profile-user-avatar rounded']")
        driver.click("//div[@class='v-avatar profile-user-avatar rounded']")
        driver.wait_for_element("//a[@href='#templates']")
        driver.click("//a[@href='#templates']")
        driver.wait_for_element("//button[@data-pendo-id='selected-template']")
        print("\nYour template message is "+driver.get_text("//button[@data-pendo-id='selected-template']/parent::div//div[contains(@class,'cardTitleForViewer')]"))
        driver.click("//a[@href='#basics']")
        driver.assert_element("//button[contains(@class,'log-out-button')]")
        driver.click("//button[contains(@class,'log-out-button')]")
        driver.wait(4)

    def test_Case2(driver):
        driver.open("https://prezent-uatstaging.myprezent.com/signin")
        driver.assert_element("#username")
        driver.type("#username", "engg_user.noreply@prezent.ai")
        driver.click("#continue")
        driver.type("#password", "kiqjemkh")
        driver.click("#submit")
        driver.wait(12)
        driver.wait_for_element("//div[@class='v-avatar profile-user-avatar rounded']")
        driver.click("//div[@class='v-avatar profile-user-avatar rounded']")
        driver.wait_for_element("//a[@href='#fingerprint']")
        driver.click("//a[@href='#fingerprint']")
        driver.scroll_to("//div[@class='btn-retake']")
        driver.click("//div[@class='btn-retake']")
        driver.wait_for_element("//span[@class='v-btn__content']")
        driver.click("//span[@class='v-btn__content']")
        driver.wait(4)
        driver.wait_for_element("//div[@class='images-wrapper']/div[2]")
        driver.click("//div[@class='images-wrapper']/div[2]")
        driver.wait(4)
        driver.wait_for_element("//div[@class='images-wrapper']/div[2]")
        driver.click("//div[@class='images-wrapper']/div[1]")
        driver.wait(4)
        driver.wait_for_element("//div[@class='images-wrapper']/div[2]")
        driver.click("//div[@class='images-wrapper']/div[1]")
        driver.wait(4)
        driver.wait_for_element("//div[@class='images-wrapper']/div[2]")
        driver.click("//div[@class='images-wrapper']/div[1]")
        driver.wait(4)
        driver.wait_for_element("//div[@class='images-wrapper']/div[2]")
        driver.click("//div[@class='images-wrapper']/div[1]")
        driver.wait(4)
        driver.wait_for_element("//div[@class='images-wrapper']/div[2]")
        driver.click("//div[@class='images-wrapper']/div[1]")
        driver.wait(4)
        driver.wait_for_element("//span[text()=' Label all charts ']")
        driver.click("//span[text()=' Label all charts ']")
        driver.click("//button[@id='show-fingerprint-for-btn--auto']")
        driver.wait_for_element("//div[@class='skip-button']")
        driver.click("//div[@class='skip-button']")
        driver.wait(2)
        driver.wait_for_element("//div[@class='skip-button']")
        driver.click("//div[@class='skip-button']")
        driver.wait(2)
        driver.wait_for_element("//div[@class='skip-button']")
        driver.click("//div[@class='skip-button']")
        driver.wait(2)
        driver.wait_for_element("//div[@class='skip-button']")
        driver.click("//div[@class='skip-button']")
        driver.wait(2)
        driver.wait_for_element("//div[@class='skip-button']")
        driver.click("//div[@class='skip-button']")
        driver.wait(2)
        driver.wait_for_element("//div[@class='skip-button']")
        driver.click("//div[@class='skip-button']")
        driver.wait(4)
        driver.wait_for_element("//span[text()=' View my fingerprint ']")
        driver.click("//span[text()=' View my fingerprint ']")
        driver.wait(8)
        driver.wait_for_element("//button[contains(@class, 'v-btn v-btn--is-elevated v-btn--has-bg v')]")
        driver.click("//button[contains(@class, 'v-btn v-btn--is-elevated v-btn--has-bg v')]")
        driver.wait_for_element("//div[@class='v-avatar profile-user-avatar rounded']")
        driver.click("//div[@class='v-avatar profile-user-avatar rounded']")
        driver.click("//a[@href='#basics']")
        driver.assert_element("//button[contains(@class,'log-out-button')]")
        driver.click("//button[contains(@class,'log-out-button')]")
        driver.wait(4)











