from seleniumbase import BaseCase

class Login(BaseCase):

    def setUp(driver):
        super().setUp()
        driver.maximize_window()
        driver.open("https://prezent-uatstaging.myprezent.com/signin")
        driver.assert_element("#username")
        driver.type("#username", "engg_user.noreply@prezent.ai")
        driver.click("#continue")
        driver.type("#password", "kiqjemkh")
        driver.click("#submit")
        driver.wait(4)
        driver.wait_for_element_visible("//div[@name='profile-icon']//div[@class='v-avatar profile-user-avatar rounded']")

    def tearDown(driver):
        driver.wait_for_element_visible("//div[@name='profile-icon']//div[@class='v-avatar profile-user-avatar rounded']")
        driver.click("//div[@name='profile-icon']//div[@class='v-avatar profile-user-avatar rounded']")
        driver.wait_for_element_visible("//a[@href='#basics']")
        driver.click("//a[@href='#basics']")
        driver.assert_element("//button[contains(@class,'log-out-button')]")
        driver.click("//button[contains(@class,'log-out-button')]")
        super().tearDown()

    def test_Case1(driver):
        driver.click("//div[@name='profile-icon']//div[@class='v-avatar profile-user-avatar rounded']")
        driver.wait_for_element_visible("//a[@href='#templates']")
        driver.click("//a[@href='#templates']")
        driver.wait(4)
        driver.wait_for_element_visible("//button[@data-pendo-id='selected-template']")
        print("\nYour template message is " + driver.get_text(
            "//button[@data-pendo-id='selected-template']/parent::div//div[contains(@class,'cardTitleForViewer')]"))

    def test_Case2(driver):
        driver.click("//div[@class='v-avatar profile-user-avatar rounded']")
        driver.wait_for_element_visible("//a[@href='#fingerprint']")
        driver.click("//a[@href='#fingerprint']")
        driver.scroll_to("//div[@class='btn-retake']")
        driver.click("//div[@class='btn-retake']")
        driver.wait_for_element_visible("//span[@class='v-btn__content']")
        driver.click("//span[@class='v-btn__content']")
        driver.wait(4)
        driver.click("//div[@class='images-wrapper']/div[2]")
        driver.wait(4)
        driver.click("//div[@class='images-wrapper']/div[1]")
        driver.wait(4)
        driver.click("//div[@class='images-wrapper']/div[1]")
        driver.wait(4)
        driver.click("//div[@class='images-wrapper']/div[1]")
        driver.wait(4)
        driver.click("//div[@class='images-wrapper']/div[1]")
        driver.wait(4)
        driver.click("//div[@class='images-wrapper']/div[1]")
        driver.wait(4)
        driver.wait_for_element_visible("//span[text()=' Label all charts ']")
        driver.click("//span[text()=' Label all charts ']")
        driver.click("//button[@id='show-fingerprint-for-btn--auto']")
        driver.wait(4)
        driver.click("//div[@class='skip-button']")
        driver.wait(4)
        driver.click("//div[@class='skip-button']")
        driver.wait(4)
        driver.click("//div[@class='skip-button']")
        driver.wait(4)
        driver.click("//div[@class='skip-button']")
        driver.wait(4)
        driver.click("//div[@class='skip-button']")
        driver.wait(4)
        driver.click("//div[@class='skip-button']")
        driver.wait(4)
        driver.wait_for_element_visible("//span[text()=' View my fingerprint ']")
        driver.click("//span[text()=' View my fingerprint ']")
        driver.wait(10)
        driver.wait_for_element_visible("//button[contains(@class, 'v-btn v-btn--is-elevated v-btn--has-bg v')]")
        driver.scroll_to("//button[contains(@class, 'v-btn v-btn--is-elevated v-btn--has-bg v')]")
        driver.click("//button[contains(@class, 'v-btn v-btn--is-elevated v-btn--has-bg v')]")

    def test_Case3(driver):
        driver.wait_for_element_visible("//div[@id='v-step-3'][@name--auto='generate']")
        driver.click("//div[@id='v-step-3'][@name--auto='generate']")
        driver.wait_for_element_visible("//textarea[@data-pendo-id='generate-propmt']")
        driver.click("//textarea[@data-pendo-id='generate-propmt']")
        driver.wait_for_element_visible("//p[@id='generate-suggested-2']")
        driver.click("//p[@id='generate-suggested-2']")
        driver.click("//button[@data-pendo-id='generate-btn']")
        driver.wait(5)
        driver.wait_for_element_visible("//video[@autoplay='autoplay']")
        driver.wait(10)
        driver.wait_for_element_not_visible("//video[@autoplay='autoplay']",timeout=70)
        driver.wait_for_element_visible("//div[@data-pendo-id='generate-template']")
        driver.wait(8)
        driver.hover("//button[@id='download']")
        driver.click("//button[@id='download'][@aria-expanded='true']")
        driver.wait_for_element_visible("//div[@class='download-actions button']")
        driver.click("//div[@class='download-actions button']")
        driver.wait_for_element_visible("//button[@id='download-btn-from-list']")
        driver.click("//button[@id='download-btn-from-list']")
        driver.wait_for_element_visible("//div[@class='slide-collection-download-header']")
        driver.wait(14)
